# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 334b4877e61daf2bc96c068cb2eb013fee74ff5ae9dcf53e67d82d035b686d375a6ec2723f504019f4592c208352f56ede0b8d7af5df5697d7cef8e09e05536c

test:
  secret_key_base: f0010e0c16090bc32d1bda6d2a9993d41bbeff5035fc29d7cc37635ae0e3bd793cdad254a3b2123ed88522015d6afbecd20ffe00ca394c686befb030dcbf448c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
